version: "3.3"
services:
  mariadb:
    image: mariadb:10.4.17
    environment:
      - MYSQL_ROOT_PASSWORD=DEV_1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - public
      - local
    hostname: mariadb
    restart: "no"
  phpmyadmin:
    image: phpmyadmin:5.0.4
    environment:
      - PMA_HOST=mariadb
    ports:
      - "127.0.0.1:8081:80"
    networks:
      - public
      - local
    depends_on:
      - mariadb
    hostname: phpmyadmin
    restart: "no"

volumes:
  mariadb-data:

networks:
  public:
    internal: false
  local:
    internal: true
